// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://quyxzrahudsveyjacptv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1eXh6cmFodWRzdmV5amFjcHR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0ODEyMTMsImV4cCI6MjA1NzA1NzIxM30.mgNkzUr2k1Q0WLVx4NEu3JEtayOvRYu8yNC2CUoVzXw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);